### ISSUE TITLE
This thing is f*cking awesome. Some simple ideas inside here!

### ISSUE THREAD

**Issue by DethMetalz69** [Amazon-Hate-it-But-Need-it/Amazon-AtoZ-VET-Flex-Bot#5]
This thing got me a whole shift today! It picks up dropped shifts really well, but I struggle to get shifts at noon each day when they do the big "main" shift drop. Even with the interval set to 1 second, it kind of stalls on the "days of the week / Find shift" page a few more seconds than that for me. At my job site, when the jobs post at noon they really are only claimable for about a second and a half. So far the bot has missed all of those. It just happens too quickly for the bot to keep up.

Is there anyway to make this thing run as fast as it possibly can with no wait interval? The only thing I can think to do is make it much faster, or to do it all with requests instead of a full browser window. 

Regardless, thank you so much for this. It's a nice tool that is like backing up my schedule on top of what shifts I can get for myself.

This thing is awesome as fuck.

**Comment by Amazon-Hate-it-But-Need-it** [comment]
You can make it run as fast as the atoz web app allows.  I updated the code and added comments to the lines that can be adjusted to decrease wait times between checks.  It might require testing different wait times on your end before finding what works for the fastest speeds when adding shifts.

**Comment by DethMetalz69** [comment]
Oh dude. This thing is fucking beastly now. I set the after login wait time to 5s and the rest to 1s. OMG. I'm gonna get a lot of fucking shifts now lol.
